# Generated by Django 5.2.6 on 2025-09-04 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiabetesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("bmi", models.FloatField()),
                ("HbA1c_level", models.FloatField()),
                ("blood_glucose_level", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeartData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("heart_rate", models.IntegerField()),
                ("systolic_bp", models.IntegerField()),
                ("diastolic_bp", models.IntegerField()),
                ("blood_sugar", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LungData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("YELLOW_FINGERS", models.BooleanField()),
                ("ANXIETY", models.BooleanField()),
                ("FATIGUE", models.BooleanField()),
                ("WHEEZING", models.BooleanField()),
                ("COUGHING", models.BooleanField()),
                ("SHORTNESS_OF_BREATH", models.BooleanField()),
                ("SWALLOWING_DIFFICULTY", models.BooleanField()),
                ("CHEST_PAIN", models.BooleanField()),
                ("LUNG_CANCER", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[(1, "Male"), (0, "Female")], max_length=10
                    ),
                ),
                ("hypertension", models.BooleanField()),
                ("heart_disease", models.BooleanField()),
                ("ALLERGY", models.BooleanField()),
                ("ALCOHOL_CONSUMING", models.BooleanField()),
                (
                    "smoking_history",
                    models.CharField(
                        choices=[
                            (0.0, "never"),
                            (1.0, "No Info"),
                            (2.0, "ever"),
                            (3.0, "former"),
                            (4.0, "current"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
