# Generated by Django 5.2.6 on 2025-09-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diabetesdata",
            name="bmi",
        ),
        migrations.AddField(
            model_name="diabetesdata",
            name="height",
            field=models.FloatField(
                blank=True, help_text="Height in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="diabetesdata",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Weight in kilograms", null=True
            ),
        ),
    ]
