# Generated by Django 5.2.6 on 2025-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_diabetesdata_bmi_diabetesdata_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diabetesdata",
            name="height",
            field=models.FloatField(default=1, help_text="Height in meters"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diabetesdata",
            name="weight",
            field=models.FloatField(default=65, help_text="Weight in kilograms"),
            preserve_default=False,
        ),
    ]
