# Generated by Django 5.2.6 on 2025-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.IntegerField(choices=[(1, "Male"), (0, "Female")]),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="smoking_history",
            field=models.FloatField(
                choices=[
                    (0.0, "never"),
                    (1.0, "No Info"),
                    (2.0, "ever"),
                    (3.0, "former"),
                    (4.0, "current"),
                ]
            ),
        ),
    ]
